
server.port=9011
server.servlet.context-path=/orders

spring.datasource.url=jdbc:postgresql://localhost:5432/orderDB
spring.datasource.username=postgres
spring.datasource.password=0000

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

resilience4j.retry.instances.inventoryRetry.max-attempts=3
resilience4j.retry.instances.inventoryRetry.wait-duration=5s
resilience4j.ratelimiter.instances.inventoryRateLimiter.limit-for-period=1
resilience4j.ratelimiter.instances.inventoryRateLimiter.limit-refresh-period=10s
resilience4j.ratelimiter.instances.inventoryRateLimiter.timeout-duration=1s



# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.register-health-indicator=true
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.wait-duration-in-open-state=20s
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.event-consumer-buffer-size=3
